# Generated by Django 6.0.4 on 2026-04-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmap',
            name='estimated_duration',
            field=models.CharField(blank=True, default='', help_text="Estimated total duration (e.g. '6-8 weeks').", max_length=100),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='overview',
            field=models.TextField(blank=True, default='', help_text='AI-generated overview/summary of the roadmap.'),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='user_input',
            field=models.TextField(blank=True, default='', help_text='Original conversational input from the user.'),
        ),
    ]
